#include <driver/timer.h>
#include <esp_log.h>
#include <math.h>

/**
 * @class PI_Controller
 * @brief Discrete Proportional–Integral (PI) controller implementation.
 *
 * This class implements a discrete-time PI controller using the
 * incremental (velocity) form of the control equation. It is designed
 * for embedded control applications such as motor control in the
 * satellite tracking system.
 *
 * The controller supports:
 * - Adjustable proportional and integral gains
 * - Output saturation
 * - Dead-zone around the error
 * - State reset
 *
 * The controller internal equation follows:
 *
 * \f[
 * u[k] = u[k-1] + a\,e[k] + b\,e[k-1]
 * \f]
 *
 * where:
 * - \f$e[k]\f$ is the current error
 * - \f$u[k]\f$ is the control output
 * - \f$a\f$ and \f$b\f$ are coefficients derived from PI gains
 *
 * This implementation is suitable for real-time control loops running
 * at fixed sampling periods.
 */
class PI_Controller
{
private:

    /**
     * @brief Controller coefficients derived from PI gains.
     */
    double a, b;

    /**
     * @brief Sampling period of the controller (seconds).
     */
    double sampleTime;

    /**
     * @brief Dead zone applied to the error signal.
     *
     * Errors with absolute value smaller than this threshold
     * are considered zero to avoid oscillations.
     */
    double deadZone = 0.0;

    /**
     * @brief Maximum absolute output value (saturation limit).
     */
    double u_max;

    /**
     * @brief Integrator internal state.
     */
    double i_f = 0.0;

    /**
     * @brief Error history buffer.
     *
     * e[0] = current error  
     * e[1] = previous error
     */
    double e[2] = {0.0,0.0};

    /**
     * @brief Control output history buffer.
     *
     * u[0] = current control output  
     * u[1] = previous control output
     */
    double u[2] = {0.0,0.0};

public:

    /**
     * @brief Construct a new PI controller.
     *
     * @param kp Proportional gain
     * @param ki Integral gain
     * @param sampleTime Controller sampling time (seconds)
     * @param deadZone Dead-zone applied to the error
     * @param u_max Maximum controller output (saturation)
     */
    PI_Controller(double kp, double ki, double sampleTime, double deadZone, double u_max);

    /**
     * @brief Update controller gains.
     *
     * Recomputes internal coefficients using the new gains.
     *
     * @param kp New proportional gain
     * @param ki New integral gain
     */
    void setGains(double kp, double ki);

    /**
     * @brief Set the maximum output value.
     *
     * This limits the controller output to avoid actuator saturation.
     *
     * @param u_max Maximum allowed control signal
     */
    void setMaxOutput(double u_max);

    /**
     * @brief Set the controller dead-zone.
     *
     * Errors smaller than this value will be ignored.
     *
     * @param deadZone Dead-zone threshold
     */
    void setDeadZone(double deadZone);

    /**
     * @brief Reset controller internal states.
     *
     * Clears integrator state, error history, and output history.
     */
    void reset();

    /**
     * @brief Compute the controller output.
     *
     * Calculates the control action given the current system
     * measurement and desired reference.
     *
     * @param input Current system measurement
     * @param setPoint Desired reference value
     *
     * @return Control signal generated by the PI controller
     */
    float output(float input, float setPoint);
};